name: Template sync

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  template-sync:
    name: Template sync
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: actions-template-sync
        uses: AndreasAugustin/actions-template-sync@v2
        with:
          source_repo_path: felix2000jp/spring-boot-template
          pr_title: "chore: repository template sync"
          pr_commit_msg: "chore: repository template sync"